# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Sleep for 120 seconds to done check
      uses: jakejarvis/wait-action@master
      with:
        time: '1s'
    
    - name: Check Base Branch
    # You may pin to the exact commit or the version.
    # uses: a-b-r-o-w-n/check-base-branch-action@f6e6e6f6d8264955f8c4c3a0d4111dfb20771bf7
      uses: a-b-r-o-w-n/check-base-branch-action@v1.1
      with:
        # Token used to interact with the Github API.
        repo-token: ${{ secrets.GIT_TOKEN }}
        # Comma separated list of branches that are protected.
        protected-branches: main
        # Branch to set as base if PR is opened against a protected branch.
        default-branch: main
    
    - name: Set NPM Token Action
      # You may pin to the exact commit or the version.
      # uses: filipstefansson/set-npm-token-action@6a5da4ef7789f70692e4d01aa969f5c602a120fa
      uses: filipstefansson/set-npm-token-action@v1.1
      with:
        # your npm token
        token: ${{ secrets.NPM_TOKEN }}
      
    - name: Setup GIT user
      uses: fregante/setup-git-user@v1
    
    - name: Bump Action
      # You may pin to the exact commit or the version.
      # uses: tool3/bump@c8e7f01fd3cfd3f58711b8e95349479c3cc2cbf6
      uses: tool3/bump@v.1.2
      with:
        # the git user to push the package.json version update
        user: Uladzimir Svirydzenka
        # the git email to push the package.json version update
        email: vladimirsviridenko1998@gmail.com
        # the git email to push the package.json version update
        branch: main
        # github access token
        github_token: ${{ secrets.GIT_TOKEN }}
    
    - name: Deploy
      run: |
        npm ci
        npm run build:dev
        npm publish ./dist
