# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Set NPM Token Action
      # You may pin to the exact commit or the version.
      # uses: filipstefansson/set-npm-token-action@6a5da4ef7789f70692e4d01aa969f5c602a120fa
      uses: filipstefansson/set-npm-token-action@v1.1
      with:
        # your npm token
        token: ${{ secrets.NPM_TOKEN }}

    - name: Setup GIT token
      # You may pin to the exact commit or the version.
      # uses: fregante/setup-git-token@614530a4b03f263cd0cc72b3217b7bac2806c342
      uses: fregante/setup-git-token@v1
      with:
        # The token provided by GitHub actions via secrets.GITHUB_TOKEN
        token: ${{ secrets.GIT_TOKEN }}
        # The name that will be used as "Author" of future commits
        name: Uladzimir Svirydzenka
        # The email that will be used as "Author" of future commits
        email: vladimirsviridenko1998@gmail.com
        
    - name: Automated Version Bump
      # You may pin to the exact commit or the version.
      # uses: phips28/gh-action-bump-version@65ec31050fe363c360baaa4fdea37a5dc829d5b0
      uses: phips28/gh-action-bump-version@v8.0.12
      with:
        skip-tag: 'true'
  
    - name: Deploy
      run: |
        npm ci
        npm run build:dev
        npm publish ./dist
