# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build & Lint
      run: |
        npm ci
        npm run lint
        npm run build:dev
    # Runs a set of commands using the runners shell
    - name: Test
      run: |
        npm ci
        npm run test-ci
  deploy:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
  
    - name: Set NPM Token Action
      # You may pin to the exact commit or the version.
      # uses: filipstefansson/set-npm-token-action@6a5da4ef7789f70692e4d01aa969f5c602a120fa
      uses: filipstefansson/set-npm-token-action@v1.1
      with:
        # your npm token
        token: ${{ secrets.NPM_TOKEN }}
    
    - name: Setup GIT user
      uses: fregante/setup-git-user@v1
  
    - name: Disable 'Include Administrator'
      # You may pin to the exact commit or the version.
      # uses: benjefferies/branch-protection-bot@29ac942cc67507dece0a73d496a841167952a3fe
      uses: benjefferies/branch-protection-bot@1.0.5
      with:
        access-token: ${{ secrets.GIT_TOKEN }}

    - name: Bump Version
      uses: phips28/gh-action-bump-version@master
      env:
        GITHUB\_TOKEN: ${{ secrets.GIT_TOKEN }}
  
    - name: Enable 'Include Administrator'
      # You may pin to the exact commit or the version.
      # uses: benjefferies/branch-protection-bot@29ac942cc67507dece0a73d496a841167952a3fe
      uses: benjefferies/branch-protection-bot@1.0.5
      with:
        access-token: ${{ secrets.GIT_TOKEN }}
  
    - name: Deploy
      run: |
        npm ci
        npm run build:dev
        npm publish ./dist
